# ClinViro
# Copyright (C) 2017 Stanford HIVDB team.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This list contains ptnum of ignored Kaiser patients which was generated by
# taking ptnum that in the exported report for Kaiser but not in Leo's list.
# These patients should be excluded from importing to HIVDB database

IGNORED_HIVDB_PATIENTS = set([int(ptnum) for ptnum in """
981
982
1021
1022
1023
1024
1025
1026
1027
39657
39811
51339
53980
56501
56506
56506
56739
57113
57212
57598
57617
57731
57779
58534
58556
58557
58557
58558
58625
58732
58733
58838
58905
58905
59071
59260
59273
59334
59367
59387
59614
59726
59789
59898
59901
59902
59916
59950
59971
60074
60197
60332
60360
60387
60691
60908
61292
61505
61578
62021
62319
63127
63436
63482
64252
64637
64935
65169""".split()])
